.nr N -1
.nr D 5
.TH VUF 1 2026\-03\-14 "vuf by viktor-chiarcos Version 1.0" 
.SH Name
vuf \- Ein Format mit der Bezeichnung "Viktors Unversal-Format"
.SH Funktionen & Befehle
\fIdecode\fP \fB'<DATEIENNAME>' '<ORDNER>'\fP

\fIdecode\fP kann dafür verwendet werden, um vuf-Dateien zu entpacken.

\fBWichtig: Für dieses Skript muss Python3.11 und die Bash installiert sein.

\fIpython3 encode.py\fP \fB -f '<DATEIENNAME>' -d '<ORDNER>'\fP

\fIencode\fP kann dafür verwendet werden, um vuf-Dateien zu verpacken.

\fBWichtig: Für dieses Skript muss Python3.11 installiert sein.

.SH Informationen & Lizenz

\fIvuf\fP ist mit der \fBGNU General Public License\fP lizensiert.

.SH Version

Letztes Update: \fI19.03.2026 13:43\fP

Page und Skripte mit \fIgit\fP \fBpull\fP Updaten